language: python
python:
  - 2.7
install:
  - sudo apt-get install python-libvirt libatlas-base-dev gfortran
  - cp /usr/lib/python2.7/dist-packages/*libvirt* ~/virtualenv/python2.7/local/lib/python2.7/site-packages/
  - pip install --use-mirrors pyqcy mocktest PyContracts nose SQLAlchemy numpy scipy
  - python setup.py install
script: nosetests
