language: python
python:
  - 2.6
  - 2.7
install:
  - sudo apt-get install -qq python-libvirt
  - pip install --use-mirrors pyqcy mocktest PyContracts nose
  - python setup.py install
script: nosetests
