language: python
python:
  - 2.7
install:
  - sudo apt-get install -qq python-libvirt python-numpy python-scipy
  - ls -al /usr/lib/python2.7/dist-packages
  - ls -al /usr/lib/python2.7/site-packages
  - cp /usr/lib/python2.7/dist-packages/*libvirt* ~/virtualenv/python2.7/local/lib/python2.7/site-packages/
  - cp -r /usr/lib/python2.7/dist-packages/*numpy* ~/virtualenv/python2.7/local/lib/python2.7/site-packages/
  - cp -r /usr/lib/python2.7/dist-packages/*scipy* ~/virtualenv/python2.7/local/lib/python2.7/site-packages/
  - pip install --use-mirrors pyqcy mocktest PyContracts nose SQLAlchemy bottle
  - python setup.py install
script: nosetests
