language: python
python:
  - 2.7
install:
  - sudo apt-get install python-libvirt python-numpy python-scipy
  - cp /usr/lib/python2.7/dist-packages/*libvirt* ~/virtualenv/python2.7/local/lib/python2.7/site-packages/
  - pip install --use-mirrors pyqcy mocktest PyContracts nose SQLAlchemy
  - python setup.py install
script: nosetests
